[functions.google-calendar-callback]
verify_jwt = false

[functions.google-calendar-event]
verify_jwt = false

[functions.freshdesk-proxy]
verify_jwt = false

[functions.openrouter-proxy]
verify_jwt = false

[auth]
site_url = "https://donccx.vercel.app"
additional_redirect_urls = ["https://donccx.vercel.app", "https://donccx.vercel.app/reset-password", "https://donccx.vercel.app/primeiro-acesso"]