export const styles = {
  timeline: {
    wrap: {
      overflowX: 'auto',
      padding: '6px 4px 4px',
      margin: '0 -4px',
    },
    row: {
      display: 'flex',
      alignItems: 'stretch',
      minWidth: 'max-content',
      gap: 0,
    },
    milestone: {
      display: 'flex',
      flexDirection: 'column',
      alignItems: 'center',
      width: '130px',
      flex: '0 0 130px',
      paddingTop: '14px',
      cursor: 'pointer',
      userSelect: 'none',
    },
    milestoneCircle: {
      width: '56px',
      height: '56px',
      borderRadius: '50%',
      background: '#fff',
      border: '2px solid rgba(15,34,58,0.18)',
      display: 'grid',
      placeItems: 'center',
      color: 'rgba(23,53,87,0.6)',
      transition: 'all 0.18s ease',
      position: 'relative',
    },
    milestoneCircleDone: {
      background: '#e7f6ee',
      borderColor: '#1aa56a',
      color: '#157a47',
    },
    milestoneCircleFuture: {
      color: 'rgba(23,53,87,0.35)',
      borderColor: 'rgba(15,34,58,0.12)',
    },
    milestoneCircleActive: {
      background: '#fff',
      borderColor: '#59c2ed',
      color: '#173557',
      boxShadow: '0 0 0 4px rgba(89,194,237,0.18)',
    },
    milestoneLabel: {
      fontSize: '12px',
      fontWeight: 600,
      marginTop: '10px',
      color: '#173557',
      textAlign: 'center',
    },
    milestoneDate: {
      fontSize: '11px',
      color: 'rgba(23,53,87,0.55)',
      marginTop: '2px',
    },
    milestoneStatus: {
      marginTop: '6px',
      fontSize: '10px',
      textTransform: 'uppercase',
      letterSpacing: '0.06em',
      color: 'rgba(23,53,87,0.5)',
      fontWeight: 600,
    },
    connector: {
      flex: '0 0 28px',
      alignSelf: 'center',
      height: '2px',
      background: 'rgba(15,34,58,0.12)',
      marginTop: '32px',
    },
    connectorDone: {
      background: '#1aa56a',
    },
    connectorActive: {
      background: 'linear-gradient(90deg, #1aa56a, #59c2ed)',
    },
    milestonePanel: {
      marginTop: '14px',
      background: '#f9fafb',
      border: '1px solid rgba(15,34,58,0.10)',
      borderRadius: '12px',
      padding: '16px 18px',
    },
  },
  activity: {
    searchWrap: {
      position: 'relative',
      marginBottom: '12px',
    },
    search: {
      width: '100%',
      padding: '9px 14px 9px 36px',
      background: '#fff',
      border: '1px solid #d4d3ce',
      borderRadius: '8px',
      fontSize: '13px',
      fontFamily: 'inherit',
      color: '#173557',
    },
    searchIcon: {
      position: 'absolute',
      left: '12px',
      top: '50%',
      transform: 'translateY(-50%)',
      color: 'rgba(23,53,87,0.4)',
      pointerEvents: 'none',
    },
    catalogDropdown: {
      position: 'absolute',
      top: 'calc(100% + 4px)',
      left: 0,
      right: 0,
      background: '#fff',
      border: '1px solid rgba(15,34,58,0.12)',
      borderRadius: '10px',
      boxShadow: '0 12px 28px rgba(10,22,40,0.12)',
      padding: '4px',
      zIndex: 5,
      maxHeight: '260px',
      overflowY: 'auto',
    },
    catalogItem: {
      padding: '8px 10px',
      borderRadius: '6px',
      fontSize: '13px',
      color: '#173557',
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'space-between',
      cursor: 'pointer',
    },
    item: {
      background: '#fff',
      border: '1px solid rgba(15,34,58,0.09)',
      borderRadius: '10px',
      transition: 'border-color 0.15s, boxShadow 0.15s',
    },
    row: {
      display: 'grid',
      gridTemplateColumns: '22px 1fr 130px 160px 110px auto',
      alignItems: 'center',
      gap: '12px',
      padding: '12px 14px',
      cursor: 'pointer',
    },
    caret: {
      width: '20px',
      height: '20px',
      display: 'grid',
      placeItems: 'center',
      color: 'rgba(23,53,87,0.4)',
      transition: 'transform 0.18s',
    },
    body: {
      borderTop: '1px solid rgba(15,34,58,0.08)',
      padding: '14px 18px 16px',
      background: '#fbfbfc',
      borderRadius: '0 0 10px 10px',
    },
  },
  pending: {
    item: {
      background: '#fff',
      border: '1px solid rgba(15,34,58,0.08)',
      borderLeft: '3px solid rgba(15,34,58,0.18)',
      borderRadius: '8px',
      padding: '9px 12px',
      display: 'grid',
      gridTemplateColumns: '1fr 110px 100px 130px 100px',
      alignItems: 'center',
      gap: '10px',
      fontSize: '12px',
    },
    blocker: {
      borderLeftColor: '#c44',
      background: 'linear-gradient(90deg, rgba(196,60,60,0.04), #fff 18%)',
    },
    high: {
      borderLeftColor: '#d99020',
    },
    title: {
      fontSize: '12px',
      fontWeight: 500,
      color: '#173557',
    },
    empty: {
      textAlign: 'center',
      padding: '14px',
      fontSize: '12px',
      color: 'rgba(23,53,87,0.5)',
      background: '#fff',
      border: '1px dashed rgba(15,34,58,0.14)',
      borderRadius: '8px',
    },
    form: {
      background: '#fff',
      border: '1px solid rgba(89,194,237,0.4)',
      borderRadius: '10px',
      padding: '14px 16px',
      marginTop: '8px',
      boxShadow: '0 4px 14px -8px rgba(89,194,237,0.4)',
    },
    formGrid: {
      display: 'grid',
      gridTemplateColumns: '1fr 1fr',
      gap: '10px 14px',
    },
    formActions: {
      display: 'flex',
      justifyContent: 'flex-end',
      gap: '8px',
      marginTop: '12px',
    },
  },
  respPicker: {
    wrap: {
      border: '1px solid #d4d3ce',
      borderRadius: '7px',
      padding: '6px',
      maxHeight: '150px',
      overflowY: 'auto',
      background: '#fff',
    },
    section: {
      fontSize: '10px',
      textTransform: 'uppercase',
      letterSpacing: '0.06em',
      color: 'rgba(23,53,87,0.5)',
      fontWeight: 600,
      padding: '5px 8px 3px',
    },
    option: {
      padding: '5px 8px',
      borderRadius: '5px',
      fontSize: '12px',
      color: '#173557',
      cursor: 'pointer',
      display: 'flex',
      alignItems: 'center',
      gap: '8px',
    },
    optionSelected: {
      background: 'rgba(89,194,237,0.12)',
      color: '#0a6a96',
      fontWeight: 500,
    },
    miniAvatar: {
      width: '20px',
      height: '20px',
      borderRadius: '50%',
      display: 'grid',
      placeItems: 'center',
      fontSize: '10px',
      fontWeight: 600,
      flexShrink: 0,
      background: 'rgba(89,194,237,0.22)',
      color: '#0a6a96',
    },
    miniAvatarTeam: {
      background: 'rgba(211,218,71,0.4)',
      color: '#5a6010',
    },
  },
};